### ISSUE TITLE
Ne marche plus avec la n0115 (avec corrections)

### ISSUE THREAD

**Issue by ghost** [sandraev/Splashtoon#1]
Hello ! Aux lignes 260 et 262, il y a cela :
`      if pixel == (248, 100, 96)`
`      elif pixel == (96, 248, 96):`
Or, avec la n0115, les couleurs ne sont plus les mêmes ! Afin que le jeu puisse être joué avec cette version, il faut remplacer cela par :
` if pixel == (248, 100, 96) or pixel == (255,101,99):`
` elif pixel == (96, 248, 96) or pixel == (99,251,99):`

**Comment by sandraev** [comment]
Salut ! Merci beaucoup de cette information ! Effectivement, la gestion des couleurs sur la Numworks (du moins sur la N110) est plus qu'aléatoire... Pour une couleur affichée à l'écran via `fill_rect()` par exemple, la couleur obtenue via `get_pixel()` sera légèrement différente.

Si cela est corrigé sur la N115, c'est une très bonne nouvelle ! En revanche, pour pallier à d'éventuels autres problèmes de ce style, je pense refactoriser le code pour utiliser uniquement les coordonnées en mode "hitbox". Le code actuel utilise un effet de bord qui a montré ses limites.

- [ ] Implémenter les hitbox au lieu de la détection des couleurs

**Comment by sandraev** [comment]
Je devrais avoir le temps de retravailler ce jeu pendant cet été. Il est également possible que je migre ce repo vers Codeberg.
